name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.
          
  call-reusable-workflow:
    needs: build
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: ${{ matrix.nodeversion }}
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    runs-on: ubuntu-latest
